#!/bin/fish
set adb $WINHOME/AppData/Local/Android/Sdk/platform-tools/adb.exe

$adb install -r (wslpath -w app/build/outputs/apk/debug/app-debug.apk)
$adb logcat -s whisper-engine RecordingService EngineManager
