#!/usr/bin/env bash
# Builds a stand-in NDK for aarch64 Linux hosts, where the NDK's x86_64 clang
# can't run. It links back to the real NDK (sysroot, clang runtime libs, CMake
# files, shader-tools) but its bin/ runs the host's clang/lld. The NDK's
# per-API target scripts (aarch64-linux-android31-clang, ...) are reused as-is:
# they only call "$bin_dir/clang".
#
# Also fetches Vulkan-Headers: the NDK sysroot has no vulkan.hpp, which ggml's
# Vulkan backend includes. The clang wrappers put it ahead of the sysroot.
#
# Prints the stand-in NDK path; rebuilt on every run (only symlinks/wrappers).
#   ANDROID_NDK_HOME=$(scripts/host-ndk.sh "$ANDROID_NDK_HOME")
set -euo pipefail

REAL_NDK="${1:?usage: host-ndk.sh <real NDK path>}"
CACHE="${LOCALRECORD_CACHE:-$HOME/.cache/localrecord}"
LLVM_VERSION="${HOST_LLVM_VERSION:-18}"
# Needs VK_HEADER_VERSION >= 301 for the vk::detail dispatcher ggml uses.
VULKAN_HEADERS_TAG="v1.4.335"
# Host LLVM tools swapped in for the NDK's x86_64 ones (as <tool>-$LLVM_VERSION).
HOST_TOOLS=(llvm-ar llvm-ranlib llvm-strip llvm-objcopy llvm-objdump llvm-nm
    llvm-readelf llvm-readobj llvm-size llvm-strings llvm-symbolizer
    llvm-addr2line llvm-cxxfilt llvm-as llvm-link ld.lld lld)

log() { echo "$@" >&2; }

host_clang="/usr/bin/clang-$LLVM_VERSION"
[ -x "$host_clang" ] || { log "missing $host_clang (apt install clang-$LLVM_VERSION lld-$LLVM_VERSION)"; exit 1; }
host_res="$("$host_clang" -print-resource-dir)"

real_prebuilt="$REAL_NDK/toolchains/llvm/prebuilt/linux-x86_64"
ndk_res="$(echo "$real_prebuilt"/lib/clang/*)"

vk_headers="$CACHE/Vulkan-Headers-$VULKAN_HEADERS_TAG"
if [ ! -f "$vk_headers/include/vulkan/vulkan.hpp" ]; then
    log "==> Fetching Vulkan-Headers $VULKAN_HEADERS_TAG"
    rm -rf "$vk_headers"
    git -c advice.detachedHead=false clone -q --depth 1 --branch "$VULKAN_HEADERS_TAG" \
        https://github.com/KhronosGroup/Vulkan-Headers "$vk_headers" >&2
fi

ndk="$CACHE/host-ndk/$(basename "$REAL_NDK")"
rm -rf "$ndk"
mkdir -p "$ndk"

for entry in "$REAL_NDK"/*; do
    [ "$(basename "$entry")" = toolchains ] || ln -s "$entry" "$ndk/"
done

prebuilt="$ndk/toolchains/llvm/prebuilt/linux-x86_64"
mkdir -p "$prebuilt/bin"
ln -s linux-x86_64 "$ndk/toolchains/llvm/prebuilt/linux-aarch64"
for entry in "$real_prebuilt"/*; do
    case "$(basename "$entry")" in
        bin | lib) ;;
        *) ln -s "$entry" "$prebuilt/" ;;
    esac
done

# Clang resource dir: host clang's builtin headers + the NDK's Android runtime
# libs (libclang_rt.builtins-*-android.a, <arch>/libunwind.a).
res="$prebuilt/lib/clang/host"
mkdir -p "$res"
ln -s "$host_res/include" "$res/include"
ln -s "$ndk_res/lib" "$res/lib"
for entry in "$real_prebuilt"/lib/*; do
    [ "$(basename "$entry")" = clang ] || ln -s "$entry" "$prebuilt/lib/"
done

write_wrapper() {
    local name="$1" driver="$2"
    cat > "$prebuilt/bin/$name" <<EOF
#!/usr/bin/env bash
# Generated by scripts/host-ndk.sh: host clang with the NDK's sysroot/runtime.
if [ "\$1" = "-cc1" ]; then
    exec "$driver" "\$@"
fi
exec "$driver" -resource-dir="$res" --sysroot="$prebuilt/sysroot" \\
    -isystem "$vk_headers/include" --rtlib=compiler-rt --unwindlib=libunwind \\
    -Wno-unused-command-line-argument "\$@"
EOF
    chmod +x "$prebuilt/bin/$name"
}
write_wrapper clang "$host_clang"
write_wrapper clang++ "/usr/bin/clang++-$LLVM_VERSION"
ln -s clang "$prebuilt/bin/$(readlink "$real_prebuilt/bin/clang")"

for script in "$real_prebuilt"/bin/*-linux-android*-clang "$real_prebuilt"/bin/*-linux-android*-clang++; do
    ln -s "$script" "$prebuilt/bin/"
done

for tool in "${HOST_TOOLS[@]}"; do
    if [ -x "/usr/bin/$tool-$LLVM_VERSION" ]; then
        ln -s "/usr/bin/$tool-$LLVM_VERSION" "$prebuilt/bin/$tool"
    fi
done
ln -s ld.lld "$prebuilt/bin/ld"

echo "$ndk"
